name: Automerge PR
on:
  workflow_run:
    workflows: ["Serverless PR"]
    types:
      - completed

env:
  DISTRIBUTOR_ROOT: "distributor"

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
          github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Fetch PR metadata artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_metadata"
            })[0];
            if (matchArtifact == null) {
              core.notice("No PR metadata found.");
              return;
            }
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_metadata.zip`, Buffer.from(download.data));
      - name: 'Grab PR metadata'
        id: pr_metadata
        run: |
          unzip pr_metadata.zip
          echo "pr=$(cat NR)" >> $GITHUB_OUTPUT
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: rebase
          MERGE_LABELS: ""
          MERGE_DELETE_BRANCH: true
          PULL_REQUEST: ${{ steps.pr_metadata.outputs.pr }}
